development:
  adapter: postgresql
  encoding: unicode
  database: my_database_development
  pool: 5
  username: postgres
  password: password
  host: localhost
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000









